<?php
//
// ZoneMinder web Quadra status view file
// Copyright (C) 2024 ZoneMinder Inc.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
//

if (!canView('System')) {
  $view = 'error';
  return;
}

require_once('includes/Quadra.php');

// Fetch initial data for first paint
$initialData = buildQuadraData();
$hasError = isset($initialData['error']);
$hasData = !$hasError && !empty($initialData['cards']);

xhtmlHeaders(__FILE__, 'Quadra Status');
getBodyTopHTML();
echo getNavBarHTML();
?>
<div id="page" class="container-fluid quadra-page">
<?php echo getPageHeaderHTML() ?>

  <div id="toolbar" class="pb-2">
    <button id="backBtn" class="btn btn-normal" data-toggle="tooltip" data-placement="top" title="<?php echo translate('Back') ?>" disabled><i class="fa fa-arrow-left"></i></button>
    <button id="refreshBtn" class="btn btn-normal" data-toggle="tooltip" data-placement="top" title="<?php echo translate('Refresh') ?>"><i class="fa fa-refresh"></i></button>
  </div>

  <div id="content">

  <!-- Top charts: VPU Usage (left) + Host Usage (right) -->
  <div class="row mb-3">
    <div class="col-md-6">
      <div class="card h-100">
        <div class="card-header"><strong>VPU Usage</strong>
          <span id="vpuTimestamp" class="text-muted small ml-2"></span>
        </div>
        <div class="card-body">
          <div id="chart-vpu-usage" style="width:100%;height:200px;"></div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card h-100">
        <div class="card-header"><strong>Host Usage</strong></div>
        <div class="card-body">
          <div id="chart-host-usage" style="width:100%;height:200px;"></div>
        </div>
      </div>
    </div>
  </div>

  <!-- VPU Devices -->
  <div id="vpuDevicesCard" class="card mb-3" style="display:none;">
    <div class="card-header">
      <i class="material-icons md-18">memory</i> VPU Devices
    </div>
    <div class="card-body table-responsive">
      <table class="table table-sm table-hover">
        <thead class="text-left">
          <tr>
            <th>Device</th>
            <th>Firmware</th>
            <th>PCIe Address</th>
            <th>NUMA</th>
          </tr>
        </thead>
        <tbody id="vpuDevicesBody"></tbody>
      </table>
    </div>
  </div>

  <!-- Per-card detail cards are generated by JS -->
  <div id="cardDetails"></div>

  <!-- Shown when there's an error or no data -->
  <div id="quadraAlert" style="display:none;"></div>

  </div><!-- content -->
</div>
<?php echo output_script_if_exists(array('assets/echarts-6.0.0/echarts.min.js'), false) ?>
<script nonce="<?php echo $cspNonce ?>">
var quadraInitialData = <?php echo json_encode($hasError ? null : ($hasData ? $initialData : null)) ?>;
var quadraInitialError = <?php echo json_encode($hasError ? $initialData['error'] : null) ?>;
</script>
<?php xhtmlFooter() ?>
